# This file defines the content types on the website. See the documentation for
# details: https://docs.bolt.cm/contenttypes/intro

categories:
  name: Categories
  singular_name: Category
  fields:
    name:
      type: text
      class: large
      group: content
      localize: true
      required: true
    slug:
      type: slug
      uses: name
      group: Meta
  icon_many: "fa:list-alt"
  icon_one: "fa:list-alt"
  locales: ['en', 'es']

collections:
  name: Collections
  singular_name: Collection
  fields:
    title:
      type: text
      class: large
      group: content
      localize: true
      required: true
    description:
      type: textarea
      group: content
      localize: true
      required: true
    image:
      type: image
      label: Feature Image
      group: content
      localize: true
      required: true
    slug:
      type: slug
      uses: title
      group: Meta
  relations:
    categories:
      multiple: true
      order: name
      label: Select Categories
      group: content
      required: true
    media:
      multiple: true
      order: title
      label: Add Media
      group: content
  taxonomy: [ media_type, tags ]
  icon_many: "fa:layer-group"
  icon_one: "fa:layer-group"
  locales: ['en', 'es']

media:
  name: Media
  singular_name: Media
  fields:
    title:
      type: text
      class: large
      group: content
      localize: true
      required: true
    description:
      type: textarea
      group: content
      required: true
    image:
      type: image
      label: Feature Image
      group: content
      localize: true
      required: true
    file:
      type: file
      label: Media File
      group: content
      localize: true
    slug:
        type: slug
        uses: title
        group: Meta
  relations:
    categories:
      multiple: true
      order: name
      label: Select Categories
      required: true
    collections:
      multiple: false
      order: title
      label: Add to a Collection
  taxonomy: [ media_type, tags ]
  icon_many: "fa:photo-video"
  icon_one: "fa:photo-video"
  locales: ['en', 'es']
