# This file defines the different types of taxonomies in Bolt. See the
# documentation for details: https://docs.bolt.cm/contenttypes/taxonomies

tags:
    slug: tags
    singular_slug: tag
    behaves_like: tags
    postfix: "Add some freeform tags. Start a new tag by typing a comma or space."
    allow_spaces: true
    #listing_template: tag-listing.twig #custom template
    required: false

media_type:
  name: Type of Media
  slug: media_type
  singular_name: Type of Media
  singular_slug: media_type
  behaves_like: categories
  multiple: false
  options: [ audio, epub, pdf, video, other ]
  required: true
